### ISSUE TITLE
KaminoAction deposit action with a separate payer account?

### ISSUE THREAD

**Issue by sourdzl** [Kamino-Finance/klend-sdk#27]
I would like to have a paymaster wallet pay for another wallet's deposit transaction costs (including state rent).  

[KaminoAction.buildDepositTxns()](https://github.com/Kamino-Finance/klend-sdk/blob/master/src/classes/action.ts#L375C1-L376C1), seems to generate the deposit transaction correctly, but it does not support passing a `payer` param to the internal call to `KaminoAction.initialize()`.

Would adding an optional `payer?: PublicKey` argument to `buildDepositTxns()` and passing it to the `initialize()` add the functionality I'm looking for?  Happy to open a PR if so.

thanks!

**Comment by elliotkennedy** [comment]
Hey @sourdzl - unfortunately the smart contract does not currently support this I don't think - https://github.com/Kamino-Finance/klend/blob/master/programs/klend/src/handlers/handler_deposit_reserve_liquidity_and_obligation_collateral.rs#L88

Currently we only have this available for permissionless repay - but the signer covers the xfer fees and the actual tokens

**Comment by sourdzl** [comment]
I see.  thank you for the quick response @elliotkennedy !

I guess I'll have to prepend a "send SOL" instruction earlier in the TXN and use the generated instruction as is, then, unless there's a better way to do this

**Comment by sourdzl** [comment]
Is this also the case for withdrawing deposits?  Those also must be funded with SOL from the user wallet, and cannot have a third party account pay for withdrawing on behalf of another user?

**Comment by elliotkennedy** [comment]
> Is this also the case for withdrawing deposits? Those also must be funded with SOL from the user wallet, and cannot have a third party account pay for withdrawing on behalf of another user?

Yes same for withdraw too I'm afraid.
